import React, { useState } from 'react';
import { BrainCircuit, Sparkles, X, Loader2 } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { Trade, TradeStats } from '../types';
import { analyzeTrades } from '../services/geminiService';

interface AIInsightsProps {
  trades: Trade[];
  stats: TradeStats;
}

export const AIInsights: React.FC<AIInsightsProps> = ({ trades, stats }) => {
  const [isOpen, setIsOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [analysis, setAnalysis] = useState<string | null>(null);

  const handleAnalyze = async () => {
    setIsOpen(true);
    if (analysis) return; // Don't re-fetch if already analyzed unless explicitly refreshed (omitted for simplicity)

    setLoading(true);
    const result = await analyzeTrades(trades, stats);
    setAnalysis(result);
    setLoading(false);
  };

  if (trades.length < 3) return null; // Only show if enough data

  return (
    <>
      <button
        onClick={handleAnalyze}
        className="flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-700 hover:to-violet-700 text-white rounded-lg font-medium shadow-lg shadow-indigo-500/20 transition-all hover:scale-105"
      >
        <Sparkles size={18} />
        Ask AI Analyst
      </button>

      {isOpen && (
        <div className="fixed inset-0 bg-black/70 backdrop-blur-sm flex items-center justify-center z-[60] p-4">
          <div className="bg-slate-900 border border-slate-700 rounded-2xl w-full max-w-2xl max-h-[80vh] flex flex-col shadow-2xl">
            {/* Header */}
            <div className="flex items-center justify-between p-6 border-b border-slate-800">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-indigo-500/20 rounded-lg">
                  <BrainCircuit className="text-indigo-400" size={24} />
                </div>
                <h2 className="text-xl font-bold text-white">Trade Analysis</h2>
              </div>
              <button 
                onClick={() => setIsOpen(false)}
                className="text-slate-400 hover:text-white transition-colors"
              >
                <X size={24} />
              </button>
            </div>

            {/* Content */}
            <div className="p-6 overflow-y-auto text-slate-300 leading-relaxed">
              {loading ? (
                <div className="flex flex-col items-center justify-center py-12 space-y-4">
                  <Loader2 className="animate-spin text-indigo-500" size={40} />
                  <p className="text-slate-400 animate-pulse">Crunching the numbers...</p>
                </div>
              ) : (
                <div className="prose prose-invert prose-sm max-w-none">
                   {/* Markdown renderer would go here, using a simple pre-wrap for now to avoid extra deps if markdown lib issues arise, 
                       but I will use a simple div since I can't easily import react-markdown in this environment without it being available.
                       Actually, I'll format the text simply.
                   */}
                   <div className="whitespace-pre-wrap font-light text-sm md:text-base">
                     {analysis}
                   </div>
                </div>
              )}
            </div>

            {/* Footer */}
            <div className="p-4 border-t border-slate-800 bg-slate-900/50 rounded-b-2xl text-center">
              <p className="text-xs text-slate-500">
                AI insights generated by Gemini. Always verify financial decisions independently.
              </p>
            </div>
          </div>
        </div>
      )}
    </>
  );
};